### ISSUE TITLE
希望提供一下支持armeabi-v7a的aar

### ISSUE THREAD

**Issue by huaxuanHan** [ccc920123/LicensePlateDemo#6]

**Comment by huaxuanHan** [comment]
谢谢大佬的幸苦奉献

**Comment by huaxuanHan** [comment]
单独测试车牌识别功能的时候，打开相机闪退，一加8T Android11
java.lang.RuntimeException: Unable to create service com.kernal.plateid.PlateRecogService: java.lang.SecurityException: getDeviceId: The user 10307 does not meet the requirements to access device identifiers.
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4349)
        at android.app.ActivityThread.access$1800(ActivityThread.java:269)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:7959)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.lang.SecurityException: getDeviceId: The user 10307 does not meet the requirements to access device identifiers.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceIdWithFeature(ITelephony.java:11520)
        at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1947)
        at com.kernal.plateid.PlateRecogService.onCreate(PlateRecogService.java:108)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4337)
        at android.app.ActivityThread.access$1800(ActivityThread.java:269) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:7959) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978) 


是因为手机版本太高了吗？获取不到设备信息？

**Comment by ccc920123** [comment]
请降低你的targetSdkVersion，compileSdkVersion 到28

**Comment by impl1874** [comment]
https://github.com/oasisfeng/condom

api30不支持获取deviceId，使用上面的库返回一个假TelephonyManager的系统实例，在Android 13使用正常
